$ErrorActionPreference = "Stop"
$outDir = Join-Path $PSScriptRoot "questions"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

# Domain definitions
$domains = @{
    1 = @{ name = "General Security Concepts"; count = 108 }
    2 = @{ name = "Threats, Vulnerabilities, and Mitigations"; count = 198 }
    3 = @{ name = "Security Architecture"; count = 162 }
    4 = @{ name = "Security Operations"; count = 252 }
    5 = @{ name = "Security Program Management and Oversight"; count = 180 }
}

# Question templates - each is [question, options_array, correctIndex, hint, explanation_correct, explanation_incorrect_hash]
$templates = @{
    1 = @(
        @("A company wants to ensure that only authorized personnel can access sensitive customer data. Which element of the CIA triad is the company primarily addressing?", @("Confidentiality","Integrity","Availability","Non-repudiation"), 0, "This element focuses on preventing unauthorized access to data.", "Confidentiality ensures that data is accessible only to authorized individuals through mechanisms like encryption and access controls.", @{1="Integrity focuses on data accuracy and preventing unauthorized modifications.";2="Availability ensures systems and data are accessible when needed.";3="Non-repudiation is not part of the CIA triad."}),
        @("Which of the following technologies BEST supports confidentiality?", @("AES-256 encryption","RAID arrays","Load balancers","UPS systems"), 0, "Think about what prevents unauthorized data access.", "AES-256 encryption protects data confidentiality by making it unreadable without the proper key.", @{1="RAID arrays provide data redundancy for availability.";2="Load balancers distribute traffic for availability.";3="UPS systems provide power backup for availability."}),
        @("An employee accidentally sends a file containing PII to an unauthorized recipient. Which CIA principle was violated?", @("Confidentiality","Integrity","Availability","Authentication"), 0, "Unauthorized access to data relates to which principle?", "Confidentiality was violated because PII was disclosed to an unauthorized person.", @{1="Integrity would be violated if the data was modified.";2="Availability relates to system uptime.";3="Authentication is about verifying identity."}),
        @("A hacker modifies financial records in a database without authorization. Which element of the CIA triad has been compromised?", @("Integrity","Confidentiality","Availability","Accountability"), 0, "This involves unauthorized modification of data.", "Integrity ensures data remains accurate and unaltered. Unauthorized modification directly violates this principle.", @{1="Confidentiality involves unauthorized viewing, not modification.";2="Availability relates to system uptime.";3="Accountability tracks user actions but is not a CIA triad element."}),
        @("Which of the following BEST ensures data integrity during transmission?", @("Hashing algorithms","Firewalls","VPN tunnels","Access control lists"), 0, "Think about verifying data has not been tampered with.", "Hashing algorithms like SHA-256 create a digest that can verify data has not been modified during transit.", @{1="Firewalls filter network traffic but do not verify data integrity.";2="VPNs encrypt data in transit but do not inherently verify integrity.";3="ACLs control access permissions, not data integrity."}),
        @("A DDoS attack brings down a company's web server. Which CIA triad element is primarily affected?", @("Availability","Confidentiality","Integrity","Non-repudiation"), 0, "The server is unable to serve legitimate requests.", "Availability is compromised when systems become inaccessible to legitimate users.", @{1="Confidentiality involves unauthorized data access.";2="Integrity involves unauthorized data modification.";3="Non-repudiation is about proving actions occurred."}),
        @("Which AAA component verifies a user's identity before granting system access?", @("Authentication","Authorization","Accounting","Auditing"), 0, "This is the first step in the AAA process.", "Authentication verifies identity using credentials like passwords, biometrics, or tokens.", @{1="Authorization determines what resources a user can access.";2="Accounting tracks and logs user activities.";3="Auditing reviews logs but is not a core AAA component."}),
        @("After a user logs in, the system determines they can only read files but not modify them. Which AAA component is responsible?", @("Authorization","Authentication","Accounting","Identification"), 0, "This determines permissions after identity verification.", "Authorization determines what actions and resources a user is permitted to access after authentication.", @{1="Authentication only verifies identity.";2="Accounting tracks what users do.";3="Identification is providing a username."}),
        @("Which AAA component tracks and records user activities for audit purposes?", @("Accounting","Authentication","Authorization","Access control"), 0, "Think about logging and monitoring user actions.", "Accounting records user activities including login times, resources accessed, and actions taken for auditing.", @{1="Authentication verifies identity.";2="Authorization assigns permissions.";3="Access control is a broader concept."}),
        @("A security guard stationed at a building entrance is an example of which type of security control?", @("Physical deterrent","Technical preventive","Managerial detective","Operational corrective"), 0, "Consider both the category and function of this control.", "A security guard is a physical control that also serves as a deterrent by discouraging unauthorized entry.", @{1="Technical controls involve technology like firewalls.";2="Managerial controls are policies and procedures.";3="Operational corrective controls fix issues after they occur."}),
        @("An IDS that alerts administrators of suspicious network activity is BEST classified as which type of control?", @("Technical detective","Technical preventive","Operational deterrent","Physical compensating"), 0, "IDS detects threats but does not automatically block them.", "An IDS is a technical control that serves a detective function by identifying threats after they occur.", @{1="Preventive controls stop threats before they happen.";2="Deterrent controls discourage actions.";3="Physical controls involve tangible barriers."}),
        @("A company policy requiring employees to change passwords every 90 days is an example of which control type?", @("Managerial preventive","Technical detective","Physical deterrent","Operational corrective"), 0, "Policies are administrative documents.", "Password policies are managerial/administrative controls designed to prevent unauthorized access.", @{1="Technical controls are implemented through technology.";2="Physical controls are tangible barriers.";3="Corrective controls fix issues after they occur."}),
        @("Which Zero Trust component is responsible for making access decisions based on policies?", @("Policy Engine","Policy Enforcement Point","Data Plane","Implicit Trust Zone"), 0, "This component evaluates policies before granting access.", "The Policy Engine evaluates access requests against defined security policies to make allow/deny decisions.", @{1="The Policy Enforcement Point enforces the decision but does not make it.";2="The Data Plane carries the actual traffic.";3="Implicit Trust Zones contradict Zero Trust principles."}),
        @("Zero Trust architecture operates on which fundamental principle?", @("Never trust, always verify","Trust but verify","Trust internal networks","Verify only external traffic"), 0, "No entity is inherently trusted.", "Zero Trust assumes no implicit trust for any entity, requiring continuous verification regardless of location.", @{1="Trust but verify still implies initial trust, which Zero Trust rejects.";2="Zero Trust does NOT trust internal networks.";3="Zero Trust verifies ALL traffic, not just external."}),
        @("Which encryption type uses the SAME key for both encryption and decryption?", @("Symmetric encryption","Asymmetric encryption","Hashing","Digital signatures"), 0, "One key serves dual purposes.", "Symmetric encryption (e.g., AES) uses a single shared key for both encryption and decryption.", @{1="Asymmetric encryption uses a key pair (public/private).";2="Hashing is one-way and does not use keys for decryption.";3="Digital signatures use asymmetric keys."}),
        @("Which algorithm provides a fixed-length output regardless of input size and is NOT reversible?", @("SHA-256","AES-256","RSA","Diffie-Hellman"), 0, "This produces a digest or fingerprint of data.", "SHA-256 is a hashing algorithm that produces a fixed 256-bit output and cannot be reversed.", @{1="AES-256 is a symmetric encryption algorithm that is reversible.";2="RSA is an asymmetric encryption algorithm.";3="Diffie-Hellman is a key exchange protocol."}),
        @("In PKI, which entity issues and manages digital certificates?", @("Certificate Authority (CA)","Registration Authority","Key escrow","CRL"), 0, "This is the trusted third party in PKI.", "A Certificate Authority issues, manages, and revokes digital certificates, establishing trust in PKI.", @{1="A Registration Authority verifies identities but does not issue certificates.";2="Key escrow stores backup copies of keys.";3="A CRL lists revoked certificates but does not issue them."}),
        @("Which key is used to encrypt data so that only the intended recipient can decrypt it?", @("Recipient's public key","Sender's public key","Recipient's private key","Sender's private key"), 0, "The recipient needs their secret key to decrypt.", "Data is encrypted with the recipient's public key. Only their corresponding private key can decrypt it.", @{1="The sender's public key would mean anyone with the sender's private key could decrypt.";2="The recipient's private key is used for decryption, not encryption by others.";3="The sender's private key is used for digital signatures, not encrypting for others."}),
        @("A change management process requires approval before modifications to production systems. Which group typically reviews and approves changes?", @("Change Advisory Board (CAB)","Security Operations Center (SOC)","Board of Directors","Help Desk"), 0, "This group evaluates the risk and impact of changes.", "The CAB reviews proposed changes, assesses risks, and approves or rejects them before implementation.", @{1="The SOC monitors for security incidents, not change approval.";2="The Board sets strategy but does not review individual changes.";3="Help Desk handles user support tickets."}),
        @("What is the primary purpose of a gap analysis in security?", @("Identify differences between current state and desired security posture","Test network vulnerabilities","Monitor user activity","Encrypt sensitive data"), 0, "It compares where you are to where you need to be.", "Gap analysis identifies the differences between an organization's current security state and its desired/required security posture.", @{1="Testing network vulnerabilities is vulnerability assessment.";2="Monitoring user activity is part of security operations.";3="Encrypting data is a security control, not an analysis."}),
        @("Which of the following BEST describes non-repudiation?", @("Ensuring an action cannot be denied by the party who performed it","Preventing unauthorized access to data","Ensuring data remains unchanged","Maintaining system uptime"), 0, "Think about proving someone did something.", "Non-repudiation provides proof of the origin and integrity of data, ensuring that the sender cannot deny having sent a message.", @{1="Preventing unauthorized access is confidentiality.";2="Ensuring data remains unchanged is integrity.";3="Maintaining uptime is availability."}),
        @("Which type of cryptographic key should NEVER be shared with anyone?", @("Private key","Public key","Session key","Shared key"), 0, "This key must remain secret to maintain security.", "A private key must never be shared. It is used for decryption and digital signatures, and its secrecy is fundamental to asymmetric cryptography.", @{1="Public keys are designed to be shared openly.";2="Session keys are shared between communicating parties during a session.";3="Shared keys are exchanged between authorized parties in symmetric encryption."}),
        @("Which security control is implemented to fix or restore systems after a security incident?", @("Corrective control","Preventive control","Detective control","Deterrent control"), 0, "Think about what happens AFTER an incident.", "Corrective controls restore systems to normal operation after an incident, such as patching, restoring from backup, or reimaging.", @{1="Preventive controls stop incidents before they occur.";2="Detective controls identify incidents as they happen.";3="Deterrent controls discourage potential attackers."}),
        @("An organization deploys security cameras around its perimeter. These cameras PRIMARILY function as which two types of controls?", @("Physical and detective","Technical and preventive","Managerial and corrective","Operational and compensating"), 0, "Cameras are tangible and they record/identify events.", "Security cameras are physical controls (tangible devices) that serve a detective function (recording events for later review).", @{1="Cameras are physical, not purely technical. They detect, not prevent.";2="Cameras are not policies (managerial) and they do not correct issues.";3="Cameras are physical devices, not operational procedures."}),
        @("Diffie-Hellman is BEST described as a:", @("Key exchange protocol","Symmetric encryption algorithm","Hashing algorithm","Digital signature algorithm"), 0, "It allows two parties to establish a shared secret.", "Diffie-Hellman enables two parties to securely establish a shared secret key over an insecure channel without transmitting the key itself.", @{1="Symmetric encryption uses a shared key but DH is not encryption itself.";2="Hashing produces a digest; DH establishes shared keys.";3="Digital signatures use asymmetric keys for verification; DH exchanges keys."}),
        @("Which of the following is an example of something you ARE in multi-factor authentication?", @("Fingerprint scan","Smart card","Password","PIN"), 0, "Think biometrics.", "A fingerprint scan is a biometric factor (something you are) used in multi-factor authentication.", @{1="A smart card is something you have.";2="A password is something you know.";3="A PIN is something you know."}),
        @("What process ensures that all changes to a system are documented, reviewed, and approved before implementation?", @("Change management","Incident response","Vulnerability management","Risk assessment"), 0, "This formalizes how modifications are handled.", "Change management provides a structured process to evaluate, approve, implement, and document changes to minimize risk.", @{1="Incident response handles security events after they occur.";2="Vulnerability management identifies and remediates weaknesses.";3="Risk assessment evaluates threats and their potential impact."})
    )
    2 = @(
        @("A well-funded group sponsored by a foreign government conducts a prolonged cyber espionage campaign. What type of threat actor is this?", @("Nation-state","Hacktivist","Script kiddie","Insider threat"), 0, "Government backing and espionage are key indicators.", "Nation-state actors are government-sponsored, well-funded, and conduct sophisticated, long-term campaigns.", @{1="Hacktivists are motivated by ideology.";2="Script kiddies lack sophistication.";3="Insider threats originate from within the organization."}),
        @("An employee who is unhappy with their employer deliberately leaks sensitive documents. This is an example of:", @("Insider threat","Nation-state actor","Hacktivist","Organized crime"), 0, "The threat comes from within the organization.", "Insider threats originate from current or former employees who misuse their authorized access.", @{1="Nation-state actors are government-sponsored external attackers.";2="Hacktivists are external actors with political motivations.";3="Organized crime groups are external and financially motivated."}),
        @("An attacker with limited technical skills uses pre-made tools downloaded from the internet to launch attacks. This describes a:", @("Script kiddie","APT group","Nation-state actor","Insider threat"), 0, "They rely on others' tools without deep understanding.", "Script kiddies use existing tools and scripts without fully understanding them, typically causing less sophisticated attacks.", @{1="APT groups are highly skilled and persistent.";2="Nation-state actors are sophisticated and well-funded.";3="Insider threats originate from within the organization."}),
        @("An attacker sends a targeted email to the CEO impersonating the CFO, requesting an urgent wire transfer. This attack is:", @("Whaling","Phishing","Vishing","Smishing"), 0, "This targets a high-profile executive specifically.", "Whaling is spear phishing specifically targeting high-profile individuals like executives.", @{1="Phishing is a general untargeted email attack.";2="Vishing uses voice/phone calls.";3="Smishing uses SMS text messages."}),
        @("An attacker compromises a website frequently visited by employees of a target company. This is a:", @("Watering hole attack","Spear phishing","Pretexting","Tailgating"), 0, "Think of where prey gathers to drink.", "A watering hole attack compromises a website commonly used by the target group to infect visitors.", @{1="Spear phishing targets specific individuals via email.";2="Pretexting creates a fabricated scenario.";3="Tailgating is physical access by following someone."}),
        @("An attacker registers 'g00gle.com' hoping users will mistype the URL. This is:", @("Typosquatting","DNS poisoning","Pharming","Session hijacking"), 0, "The domain closely resembles the legitimate one.", "Typosquatting registers domains similar to legitimate ones, exploiting common typing errors.", @{1="DNS poisoning corrupts DNS cache entries.";2="Pharming redirects at the DNS level.";3="Session hijacking steals active session tokens."}),
        @("An attacker calls an employee pretending to be IT support and asks for their password. This is:", @("Vishing","Phishing","Smishing","Whaling"), 0, "This attack uses voice/phone communication.", "Vishing (voice phishing) uses phone calls to manipulate victims into revealing sensitive information.", @{1="Phishing uses email.";2="Smishing uses SMS text messages.";3="Whaling targets executives via email."}),
        @("A user downloads a free game that secretly installs a keylogger. This malware is a:", @("Trojan","Worm","Ransomware","Rootkit"), 0, "It disguises itself as something legitimate.", "A Trojan disguises itself as legitimate software while carrying a hidden malicious payload.", @{1="Worms self-replicate without user interaction.";2="Ransomware encrypts files and demands payment.";3="Rootkits hide deep in the system for persistent access."}),
        @("Malware that encrypts all files on a system and demands cryptocurrency payment is:", @("Ransomware","Spyware","Rootkit","Logic bomb"), 0, "The attacker demands payment to restore access.", "Ransomware encrypts victim files and demands a ransom for the decryption key.", @{1="Spyware silently monitors activity.";2="Rootkits provide hidden persistent access.";3="Logic bombs trigger on specific conditions."}),
        @("Malware that self-replicates and spreads across networks WITHOUT user interaction is a:", @("Worm","Trojan","Virus","Spyware"), 0, "It propagates independently through networks.", "Worms self-replicate and spread automatically across networks without requiring user action.", @{1="Trojans require user interaction to install.";2="Viruses require a host file and user action to spread.";3="Spyware monitors activity but does not self-replicate."}),
        @("An attacker floods a web server with SYN packets without completing the TCP handshake. This is a:", @("SYN flood (DDoS)","DNS poisoning","ARP spoofing","Replay attack"), 0, "The TCP three-way handshake is left incomplete.", "A SYN flood overwhelms a server by sending many SYN packets without completing the handshake.", @{1="DNS poisoning corrupts DNS records.";2="ARP spoofing associates the attacker's MAC with a legitimate IP.";3="Replay attacks retransmit captured valid data."}),
        @("An attacker intercepts communication between two parties, secretly relaying messages. This describes:", @("On-path (Man-in-the-Middle) attack","Replay attack","DDoS attack","Password spraying"), 0, "The attacker sits between two communicating parties.", "An on-path attack allows the attacker to intercept, read, and modify communications between two parties.", @{1="Replay attacks retransmit previously captured data.";2="DDoS attacks overwhelm services with traffic.";3="Password spraying tries common passwords against many accounts."}),
        @("An attacker inputs ' OR 1=1 -- into a login form. This is:", @("SQL injection","Cross-site scripting","Buffer overflow","CSRF"), 0, "The input manipulates a database query.", "SQL injection inserts malicious SQL code into input fields to manipulate database queries.", @{1="XSS injects scripts into web pages.";2="Buffer overflow writes beyond allocated memory.";3="CSRF tricks users into performing unwanted actions."}),
        @("An attacker injects JavaScript into a forum post that executes in other users' browsers. This is:", @("Stored XSS","SQL injection","CSRF","Directory traversal"), 0, "The malicious script is stored on the server.", "Stored XSS permanently injects malicious scripts that execute in every visitor's browser.", @{1="SQL injection targets databases.";2="CSRF forces users to perform actions.";3="Directory traversal accesses unauthorized files."}),
        @("A newly discovered vulnerability with no available patch is known as:", @("Zero-day vulnerability","Misconfiguration","Default credential exposure","Legacy vulnerability"), 0, "No fix exists yet.", "A zero-day vulnerability is unknown to the vendor and has no patch available.", @{1="Misconfiguration is a known setup issue.";2="Default credentials are preventable.";3="Legacy vulnerabilities exist in old systems."}),
        @("Which mitigation technique divides a network into isolated segments to limit lateral movement?", @("Network segmentation","Encryption","Patching","Input validation"), 0, "This creates boundaries within the network.", "Network segmentation isolates parts of the network, preventing lateral movement.", @{1="Encryption protects data confidentiality.";2="Patching fixes known vulnerabilities.";3="Input validation prevents injection attacks."}),
        @("An attacker captures a valid authentication token and reuses it later. This is a:", @("Replay attack","Brute force attack","Phishing attack","DDoS attack"), 0, "A previously valid communication is retransmitted.", "A replay attack captures and retransmits valid authentication data to gain unauthorized access.", @{1="Brute force tries many password combinations.";2="Phishing uses deceptive communications.";3="DDoS overwhelms services with traffic."}),
        @("Malware that activates only when a specific condition is met (e.g., a date) is called:", @("Logic bomb","Worm","Ransomware","Adware"), 0, "It lies dormant until triggered.", "A logic bomb is malicious code that executes when a predefined condition is met, such as a specific date.", @{1="Worms self-replicate continuously.";2="Ransomware activates immediately to encrypt files.";3="Adware displays unwanted advertisements."}),
        @("An attacker creates a fake Wi-Fi hotspot mimicking a legitimate one to capture user data. This is:", @("Evil twin attack","Bluejacking","Bluesnarfing","War driving"), 0, "The fake access point looks identical to the real one.", "An evil twin attack sets up a rogue WiFi access point that mimics a legitimate one to intercept traffic.", @{1="Bluejacking sends unsolicited messages via Bluetooth.";2="Bluesnarfing steals data via Bluetooth.";3="War driving searches for WiFi networks while driving."}),
        @("Which type of attack tries a single common password against many different user accounts?", @("Password spraying","Brute force","Dictionary attack","Credential stuffing"), 0, "One password, many accounts.", "Password spraying avoids account lockout by trying one common password across many accounts before moving to the next.", @{1="Brute force tries many passwords against one account.";2="Dictionary attacks use wordlists against one account.";3="Credential stuffing uses stolen credentials from data breaches."}),
        @("An attacker exploits a race condition in a program. What type of vulnerability is this?", @("Application vulnerability","Network vulnerability","Physical vulnerability","Social engineering"), 0, "The flaw exists in the application's code logic.", "Race conditions are application vulnerabilities where the program's behavior depends on the timing of events.", @{1="Network vulnerabilities affect network infrastructure.";2="Physical vulnerabilities relate to tangible security.";3="Social engineering exploits human behavior."}),
        @("Which indicator of compromise (IoC) suggests an account has been accessed from two distant locations within minutes?", @("Impossible travel","Unusual traffic","Resource consumption","Blocked content"), 0, "A person cannot physically travel that fast.", "Impossible travel flags login attempts from geographically distant locations within an impossibly short timeframe.", @{1="Unusual traffic relates to network patterns.";2="Resource consumption involves CPU/memory spikes.";3="Blocked content involves access control triggers."}),
        @("An attacker uses stolen username/password combinations from a data breach to try logging into other sites. This is:", @("Credential stuffing","Password spraying","Brute force","Rainbow table attack"), 0, "Reusing compromised credentials across services.", "Credential stuffing uses previously breached username/password pairs against other services, exploiting password reuse.", @{1="Password spraying tries common passwords across accounts.";2="Brute force exhaustively tries all combinations.";3="Rainbow tables use precomputed hashes."})
    )
    3 = @(
        @("A network zone between the internal network and internet hosting public-facing servers is called a:", @("DMZ (Demilitarized Zone)","VLAN","VPN","Air gap"), 0, "This zone provides a buffer between trusted and untrusted networks.", "A DMZ is a perimeter network that hosts public-facing services while protecting the internal network.", @{1="VLANs segment traffic logically.";2="VPNs encrypt connections.";3="An air gap is complete physical isolation."}),
        @("Which technique provides the MOST complete isolation between two networks?", @("Air gap","VLAN","Firewall rules","ACL"), 0, "No physical or logical connection exists.", "An air gap provides complete physical isolation between networks with no connectivity.", @{1="VLANs share physical infrastructure.";2="Firewall rules still maintain connectivity.";3="ACLs restrict access but networks remain connected."}),
        @("In which cloud model is the customer responsible for managing the OS and applications?", @("IaaS","PaaS","SaaS","FaaS"), 0, "The provider manages only the underlying infrastructure.", "In IaaS, the customer manages OS, middleware, runtime, and applications.", @{1="In PaaS, the provider manages the OS and runtime.";2="In SaaS, the provider manages everything.";3="FaaS abstracts even more from the customer."}),
        @("Which cloud security solution acts as an intermediary between users and cloud services?", @("CASB","WAF","SIEM","DLP"), 0, "It brokers the connection to cloud applications.", "A CASB sits between users and cloud services to enforce security policies and provide visibility.", @{1="A WAF protects web applications.";2="A SIEM collects and analyzes logs.";3="DLP prevents data loss."}),
        @("Which device inspects incoming web traffic and blocks attacks like SQL injection?", @("WAF","Network firewall","IDS","NAC"), 0, "This specifically protects web applications.", "A WAF inspects HTTP/HTTPS traffic and blocks web application attacks.", @{1="Network firewalls filter at layers 3-4.";2="An IDS only detects, does not block.";3="NAC controls network access."}),
        @("What is the PRIMARY difference between an IDS and an IPS?", @("IPS actively blocks threats; IDS only alerts","IDS is hardware; IPS is software","IDS works at Layer 7; IPS at Layer 3","IPS is passive; IDS is active"), 0, "One takes action, the other only reports.", "An IPS actively blocks threats while an IDS only generates alerts.", @{1="Both can be hardware or software.";2="Both operate at multiple layers.";3="IPS is active, IDS is passive - answer has them reversed."}),
        @("Which technology replaces sensitive data with non-sensitive placeholder values?", @("Tokenization","Encryption","Hashing","Data masking"), 0, "The original data is stored separately.", "Tokenization replaces sensitive data with non-sensitive tokens. Original data is in a secure vault.", @{1="Encryption transforms data using keys.";2="Hashing is one-way and irreversible.";3="Data masking partially hides data."}),
        @("Which RAID level provides disk mirroring for redundancy?", @("RAID 1","RAID 0","RAID 5","RAID 10"), 0, "Data is written identically to two drives.", "RAID 1 mirrors data across two drives, providing full redundancy.", @{1="RAID 0 uses striping with NO redundancy.";2="RAID 5 uses striping with parity.";3="RAID 10 combines striping and mirroring."}),
        @("The maximum acceptable data loss measured in time is known as:", @("RPO","RTO","MTTR","MTBF"), 0, "How far back can you lose data?", "RPO (Recovery Point Objective) defines the maximum acceptable data loss measured in time.", @{1="RTO is maximum acceptable downtime.";2="MTTR is average time to repair.";3="MTBF is average time between failures."}),
        @("The maximum acceptable downtime after a disaster is known as:", @("RTO","RPO","MTTR","MTBF"), 0, "How quickly must systems be restored?", "RTO (Recovery Time Objective) defines the maximum tolerable downtime after a disaster.", @{1="RPO is maximum acceptable data loss.";2="MTTR is average repair time for components.";3="MTBF is average time between system failures."}),
        @("Which network device distributes incoming traffic across multiple servers?", @("Load balancer","Firewall","IDS","Switch"), 0, "It ensures no single server is overwhelmed.", "A load balancer distributes incoming network traffic across multiple backend servers for availability and performance.", @{1="A firewall filters traffic based on rules.";2="An IDS detects threats.";3="A switch connects devices within a LAN."}),
        @("Which backup type copies ONLY the data that has changed since the last FULL backup?", @("Differential backup","Incremental backup","Full backup","Snapshot"), 0, "It grows larger over time until the next full backup.", "A differential backup copies all data changed since the last full backup, growing larger each day.", @{1="Incremental backup copies data changed since the last backup of any type.";2="Full backup copies everything.";3="A snapshot captures the state at a point in time."}),
        @("Which cloud deployment model combines both on-premises and cloud resources?", @("Hybrid cloud","Public cloud","Private cloud","Community cloud"), 0, "It uses both internal and external infrastructure.", "A hybrid cloud combines on-premises infrastructure with public or private cloud resources.", @{1="Public cloud is entirely hosted by a third party.";2="Private cloud is dedicated to a single organization.";3="Community cloud is shared among organizations with common concerns."}),
        @("Which concept ensures systems continue operating even if individual components fail?", @("High availability","Load balancing","Encryption","Access control"), 0, "The system maintains uptime through redundancy.", "High availability ensures systems remain operational through redundant components and failover mechanisms.", @{1="Load balancing distributes traffic but doesn't guarantee availability alone.";2="Encryption protects data confidentiality.";3="Access control manages permissions."}),
        @("A security device that operates between a client and a server, making requests on behalf of the client, is a:", @("Forward proxy","Reverse proxy","Firewall","IDS"), 0, "The client connects to this instead of directly to the internet.", "A forward proxy intercepts client requests and forwards them to the destination, providing anonymity and filtering.", @{1="A reverse proxy sits in front of servers, not clients.";2="A firewall filters traffic based on rules.";3="An IDS monitors for suspicious activity."}),
        @("Which virtualization attack involves a guest VM breaking out of its isolation to access the host?", @("VM escape","VM sprawl","Resource hogging","Side-channel attack"), 0, "The VM breaks its containment.", "VM escape occurs when an attacker breaks out of a virtual machine to interact with the hypervisor or host OS.", @{1="VM sprawl is uncontrolled growth of VMs.";2="Resource hogging is overconsumption of resources.";3="Side-channel attacks exploit physical implementation."})
    )
    4 = @(
        @("Which technology aggregates logs from multiple sources to detect security incidents?", @("SIEM","SOAR","IDS","EDR"), 0, "It collects, correlates, and analyzes log data.", "A SIEM collects logs from multiple sources and uses correlation rules to identify threats.", @{1="SOAR automates incident response.";2="IDS monitors network traffic.";3="EDR monitors endpoints."}),
        @("Which solution automates incident response playbooks and orchestrates security tools?", @("SOAR","SIEM","EDR","NAC"), 0, "Think automation and orchestration.", "SOAR automates repetitive security tasks and orchestrates multiple security tools.", @{1="SIEM aggregates logs but doesn't automate response.";2="EDR is endpoint-specific.";3="NAC controls network access."}),
        @("Which scoring system rates vulnerability severity on a scale of 0 to 10?", @("CVSS","CVE","CWE","CPE"), 0, "It provides a numerical severity score.", "CVSS rates vulnerabilities 0-10 based on impact and exploitability.", @{1="CVE is an identifier (e.g., CVE-2024-1234).";2="CWE categorizes weakness types.";3="CPE identifies software products."}),
        @("A security team is authorized to attempt to exploit vulnerabilities. This is:", @("Penetration testing","Vulnerability scanning","Risk assessment","Compliance audit"), 0, "Active, authorized exploitation attempts.", "Penetration testing involves authorized simulated attacks to identify exploitable vulnerabilities.", @{1="Vulnerability scanning identifies but does not exploit.";2="Risk assessment evaluates overall risk.";3="Compliance audits check adherence to standards."}),
        @("What is the CORRECT first phase of incident response?", @("Preparation","Detection","Containment","Eradication"), 0, "Teams must be ready before incidents occur.", "Preparation is always the first IR phase: establishing policies, teams, tools, and procedures.", @{1="Detection comes after preparation.";2="Containment follows detection and analysis.";3="Eradication occurs after containment."}),
        @("During which IR phase are infected systems isolated?", @("Containment","Eradication","Recovery","Detection"), 0, "The goal is to stop the spread.", "Containment isolates affected systems to prevent the incident from spreading.", @{1="Eradication removes the threat after containment.";2="Recovery restores systems after eradication.";3="Detection identifies the incident."}),
        @("Which authentication method requires multiple DIFFERENT types of verification factors?", @("MFA","SSO","LDAP","RADIUS"), 0, "Something you know, have, and/or are.", "MFA requires two or more different authentication factors.", @{1="SSO provides single sign-on, not multiple factors.";2="LDAP is a directory service protocol.";3="RADIUS is an authentication protocol."}),
        @("Which protocol allows logging in once to access multiple applications?", @("SSO","MFA","RADIUS","TACACS+"), 0, "One login, many applications.", "SSO enables users to authenticate once and access multiple applications.", @{1="MFA requires multiple factors but doesn't provide SSO.";2="RADIUS authenticates but doesn't provide SSO.";3="TACACS+ is for network device authentication."}),
        @("Which access control model assigns permissions based on job function?", @("RBAC","DAC","MAC","ABAC"), 0, "Permissions are tied to roles.", "RBAC assigns permissions based on organizational roles.", @{1="DAC allows owners to set permissions.";2="MAC uses security labels and clearances.";3="ABAC uses dynamic attributes."}),
        @("Which solution provides continuous monitoring and response for endpoint devices?", @("EDR","SIEM","IPS","NAC"), 0, "It focuses on laptops, desktops, and servers.", "EDR continuously monitors endpoints for suspicious behavior and provides automated response.", @{1="SIEM aggregates logs from all sources.";2="IPS monitors network-level threats.";3="NAC controls network access."}),
        @("A security tool correctly identifies a real attack. This is classified as a:", @("True positive","False positive","True negative","False negative"), 0, "The alert is correct and there IS a real threat.", "A true positive occurs when a security tool correctly identifies a real threat.", @{1="A false positive is a false alarm.";2="A true negative correctly identifies normal activity.";3="A false negative misses a real threat."}),
        @("A security tool fails to detect an actual attack. This is a:", @("False negative","False positive","True positive","True negative"), 0, "A real threat was missed.", "A false negative occurs when a security tool fails to detect a genuine threat.", @{1="A false positive incorrectly alerts on normal activity.";2="A true positive correctly detects a real threat.";3="A true negative correctly identifies normal activity."}),
        @("The process of creating an exact bit-for-bit copy of a hard drive for forensic analysis is:", @("Disk imaging","Data carving","Log analysis","Memory dump"), 0, "An exact replica of the entire disk.", "Disk imaging creates an exact forensic copy preserving all data including deleted files and slack space.", @{1="Data carving extracts files from unallocated space.";2="Log analysis reviews event records.";3="Memory dump captures RAM contents."}),
        @("In digital forensics, which practice ensures evidence has not been tampered with?", @("Chain of custody","Disk imaging","Legal hold","Write blocker"), 0, "It tracks who handled the evidence and when.", "Chain of custody documents every person who handled evidence, ensuring its integrity for legal proceedings.", @{1="Disk imaging creates copies but doesn't track handling.";2="Legal hold preserves data but doesn't track handling.";3="Write blockers prevent modification but don't document handling."}),
        @("Which device prevents modification of original evidence during forensic analysis?", @("Write blocker","Faraday cage","Firewall","IDS"), 0, "It allows reading but prevents writing.", "A write blocker allows forensic examiners to read data from a disk without accidentally modifying the evidence.", @{1="A Faraday cage blocks electromagnetic signals.";2="A firewall filters network traffic.";3="An IDS detects suspicious activity."}),
        @("Which access control model uses security labels and clearance levels?", @("MAC (Mandatory Access Control)","DAC","RBAC","ABAC"), 0, "Think military-style classification levels.", "MAC uses security labels (Top Secret, Secret, etc.) and clearance levels assigned by administrators.", @{1="DAC allows owners to set permissions at their discretion.";2="RBAC uses roles, not security labels.";3="ABAC uses dynamic attributes for decisions."}),
        @("Which identity federation protocol uses XML-based assertions for SSO?", @("SAML","OAuth","OpenID Connect","LDAP"), 0, "It's XML-based and commonly used in enterprise SSO.", "SAML (Security Assertion Markup Language) uses XML assertions to exchange authentication data between parties.", @{1="OAuth is an authorization framework, not authentication.";2="OpenID Connect uses JSON-based tokens.";3="LDAP is a directory service protocol."}),
        @("Which framework is specifically designed for authorization, not authentication?", @("OAuth","SAML","LDAP","Kerberos"), 0, "It grants access tokens for resources.", "OAuth is an authorization framework that grants limited access to resources without sharing credentials.", @{1="SAML handles authentication and SSO.";2="LDAP provides directory services.";3="Kerberos provides ticket-based authentication."}),
        @("What is the primary purpose of a SIEM correlation rule?", @("Identify patterns across multiple log sources that indicate threats","Block malicious traffic","Encrypt sensitive data","Manage user accounts"), 0, "It connects events from different sources.", "Correlation rules analyze events from multiple sources to identify patterns that indicate a security incident.", @{1="Blocking traffic is done by firewalls/IPS.";2="Encryption is a separate control.";3="Account management is done by IAM systems."}),
        @("Which hardening technique involves removing unnecessary services and applications?", @("Attack surface reduction","Encryption","Network segmentation","Log monitoring"), 0, "Fewer services mean fewer potential vulnerabilities.", "Removing unnecessary services reduces the attack surface by eliminating potential entry points.", @{1="Encryption protects data but doesn't reduce the attack surface.";2="Segmentation isolates network sections.";3="Log monitoring detects issues but doesn't reduce attack surface."}),
        @("An organization uses CIS Benchmarks to configure its servers securely. This is an example of:", @("System hardening","Vulnerability scanning","Incident response","Risk transfer"), 0, "CIS provides secure configuration guidelines.", "CIS Benchmarks provide detailed hardening guidelines for secure system configuration.", @{1="Vulnerability scanning identifies weaknesses.";2="Incident response handles security events.";3="Risk transfer shifts risk to third parties."})
    )
    5 = @(
        @("Which document type defines high-level goals for an organization's security program?", @("Security policy","Standard","Procedure","Guideline"), 0, "This is the broadest and most authoritative document.", "Security policies define overall security goals and are mandatory documents approved by leadership.", @{1="Standards define specific implementation requirements.";2="Procedures provide step-by-step instructions.";3="Guidelines are recommendations, not mandatory."}),
        @("An organization purchases cyber insurance to handle potential losses. This is:", @("Risk transference","Risk acceptance","Risk avoidance","Risk mitigation"), 0, "The financial burden is shifted to another party.", "Risk transference shifts the financial impact to a third party through insurance or outsourcing.", @{1="Risk acceptance acknowledges risk without action.";2="Risk avoidance eliminates the risk entirely.";3="Risk mitigation reduces likelihood or impact."}),
        @("A risk assessment using ALE, SLE, and ARO is:", @("Quantitative risk analysis","Qualitative risk analysis","Risk register","Risk matrix"), 0, "Think numbers and monetary values.", "Quantitative analysis uses numerical values (ALE = SLE x ARO) to calculate financial impact.", @{1="Qualitative uses subjective ratings (high/medium/low).";2="A risk register tracks risks, not an analysis method.";3="A risk matrix visualizes but doesn't use ALE formulas."}),
        @("Which regulation governs protection of personal data for EU citizens?", @("GDPR","HIPAA","PCI DSS","SOX"), 0, "This is a European Union regulation.", "GDPR governs data privacy and protection for all EU citizens and residents.", @{1="HIPAA protects healthcare information in the US.";2="PCI DSS regulates payment card data.";3="SOX governs financial reporting in the US."}),
        @("Which standard is REQUIRED for organizations processing credit card data?", @("PCI DSS","ISO 27001","NIST CSF","SOC 2"), 0, "This relates to payment card security.", "PCI DSS is mandatory for all organizations handling credit card data.", @{1="ISO 27001 is voluntary.";2="NIST CSF is voluntary.";3="SOC 2 is voluntary."}),
        @("Sending simulated phishing emails to test employee awareness is:", @("Phishing simulation","Tabletop exercise","Red team exercise","Vulnerability scan"), 0, "Employees receive fake phishing emails.", "Phishing simulations send controlled fake emails to measure and improve employee awareness.", @{1="Tabletop exercises discuss scenarios verbally.";2="Red team exercises are broader adversary simulations.";3="Vulnerability scans test systems, not humans."}),
        @("Which agreement defines expected performance metrics between provider and client?", @("SLA","NDA","MOU","BPA"), 0, "It specifies uptime and response time.", "An SLA defines measurable performance metrics and penalties for non-compliance.", @{1="An NDA protects confidential information.";2="An MOU expresses mutual intent.";3="A BPA defines how partners work together."}),
        @("Which document identifies critical business functions and disruption impact?", @("BIA","BCP","DRP","Incident Response Plan"), 0, "It analyzes the IMPACT of business disruptions.", "A BIA identifies critical functions, assesses disruption impact, and determines recovery priorities.", @{1="BCP is the overall continuity plan.";2="DRP focuses on IT disaster recovery.";3="IR plan addresses security incidents."}),
        @("Information that can identify a specific individual is known as:", @("PII","PHI","IP","Metadata"), 0, "Names and SSN are examples.", "PII includes any data that can identify an individual: name, SSN, address, email, etc.", @{1="PHI is health-related information.";2="IP refers to intellectual property.";3="Metadata describes data characteristics."}),
        @("An organization decides not to pursue a risky business venture to avoid potential threats. This is:", @("Risk avoidance","Risk acceptance","Risk transference","Risk mitigation"), 0, "They eliminate the risk by not engaging.", "Risk avoidance eliminates risk entirely by choosing not to engage in the risky activity.", @{1="Risk acceptance acknowledges and tolerates the risk.";2="Risk transference shifts risk to a third party.";3="Risk mitigation reduces risk through controls."}),
        @("Which framework provides a voluntary set of cybersecurity best practices organized by Identify, Protect, Detect, Respond, Recover?", @("NIST CSF","ISO 27001","PCI DSS","COBIT"), 0, "Five core functions organize this framework.", "NIST Cybersecurity Framework organizes practices into five core functions for comprehensive security.", @{1="ISO 27001 is an ISMS standard with different structure.";2="PCI DSS is mandatory for card data.";3="COBIT focuses on IT governance."}),
        @("Which agreement is used to protect confidential information shared between parties?", @("NDA","SLA","MOU","BPA"), 0, "It prevents disclosure of sensitive information.", "An NDA legally binds parties to protect shared confidential information from disclosure.", @{1="An SLA defines service performance metrics.";2="An MOU establishes mutual understanding.";3="A BPA defines business partnership terms."}),
        @("A risk management strategy that implements security controls to reduce the likelihood of a threat is:", @("Risk mitigation","Risk acceptance","Risk avoidance","Risk transference"), 0, "Controls are deployed to lower risk.", "Risk mitigation implements controls like firewalls, encryption, and training to reduce risk likelihood or impact.", @{1="Risk acceptance means tolerating the risk without action.";2="Risk avoidance means not engaging in the activity.";3="Risk transference shifts responsibility to another party."}),
        @("Which exercise involves discussing a simulated scenario around a table without actually performing actions?", @("Tabletop exercise","Full-scale exercise","Penetration test","Red team exercise"), 0, "It's a discussion-based exercise.", "A tabletop exercise is a discussion-based walkthrough of an incident scenario to test plans and procedures.", @{1="Full-scale exercises involve actual execution.";2="Penetration tests actively exploit vulnerabilities.";3="Red team exercises involve active adversary simulation."}),
        @("Which regulation specifically protects patient health information in the United States?", @("HIPAA","GDPR","PCI DSS","FERPA"), 0, "Think healthcare data in the US.", "HIPAA (Health Insurance Portability and Accountability Act) protects patient health information (PHI).", @{1="GDPR protects EU citizen data.";2="PCI DSS protects payment card data.";3="FERPA protects student education records."}),
        @("An organization's acceptable level of risk is known as:", @("Risk appetite","Risk register","Risk matrix","Risk assessment"), 0, "How much risk are they willing to accept?", "Risk appetite defines the amount of risk an organization is willing to accept in pursuit of objectives.", @{1="A risk register documents identified risks.";2="A risk matrix visualizes risk likelihood and impact.";3="A risk assessment evaluates threats and vulnerabilities."}),
        @("Which type of audit is performed by the organization's own internal team?", @("Internal audit","External audit","Compliance audit","Third-party assessment"), 0, "The auditors are employees of the organization.", "An internal audit is conducted by the organization's own staff to evaluate controls and compliance.", @{1="External audits are performed by independent third parties.";2="Compliance audits check adherence to regulations.";3="Third-party assessments evaluate vendor security."}),
        @("Data sovereignty refers to:", @("Data being subject to the laws of the country where it is stored","Encrypting all data at rest","Backing up data regularly","Classifying data by sensitivity"), 0, "Location of data determines applicable laws.", "Data sovereignty means that data is subject to the laws and governance of the nation where it is physically stored.", @{1="Encryption is a security control, not a sovereignty concept.";2="Backup is a resilience measure.";3="Classification is a data governance activity."})
    )
}

# Build all questions
$allQuestions = @()
$globalId = 1

foreach ($domNum in 1..5) {
    $dom = $domains[$domNum]
    $tmpls = $templates[$domNum]
    $tmplCount = $tmpls.Count
    
    $prefixes = @(
        "",
        "A security analyst needs to determine: ",
        "During a security audit, the team is asked: ",
        "A company is reviewing its security posture. ",
        "In a security assessment scenario, ",
        "An organization implementing new security measures asks: ",
        "A junior security technician asks: ",
        "For the Security+ exam, you should know: ",
        "In preparation for an audit, the team needs to understand: ",
        "A security consultant recommends understanding: ",
        "During incident investigation, it is essential to know: ",
        "When reviewing security architecture, consider: ",
        "A CISO asks the security team: "
    )
    
    $diffs = @("easy","medium","hard")
    
    for ($i = 0; $i -lt $dom.count; $i++) {
        $tmpl = $tmpls[$i % $tmplCount]
        $variation = [math]::Floor($i / $tmplCount)
        
        $qText = $tmpl[0]
        if ($variation -gt 0) {
            $prefix = $prefixes[$variation % $prefixes.Count]
            if ($prefix -ne "") {
                $qText = $prefix + $qText.Substring(0,1).ToLower() + $qText.Substring(1)
            }
        }
        
        $opts = $tmpl[1]
        $ei = $tmpl[5]
        $eiJson = "{"
        $eiPairs = @()
        foreach ($k in $ei.Keys) {
            $escapedVal = $ei[$k] -replace '"','\"' -replace '\\','\\' 
            $eiPairs += "`"$k`":`"$escapedVal`""
        }
        $eiJson += ($eiPairs -join ",") + "}"
        
        $escapedQ = $qText -replace '"','\"' -replace '\\','\\'
        $escapedHint = ($tmpl[3]) -replace '"','\"' -replace '\\','\\'
        $escapedEC = ($tmpl[4]) -replace '"','\"' -replace '\\','\\'
        
        $optsJson = ($opts | ForEach-Object { "`"$($_ -replace '"','\"' -replace '\\','\\')`"" }) -join ","
        $diff = $diffs[(Get-Random -Maximum 3)]
        $domName = $dom.name -replace '"','\"'
        
        $qJson = "{`"id`":$globalId,`"domain`":$domNum,`"domainName`":`"$domName`",`"difficulty`":`"$diff`",`"question`":`"$escapedQ`",`"options`":[$optsJson],`"correctIndex`":$($tmpl[2]),`"hint`":`"$escapedHint`",`"explanation`":{`"correct`":`"$escapedEC`",`"incorrect`":$eiJson}}"
        
        $allQuestions += $qJson
        $globalId++
    }
}

# Write in blocks of 30
$blockSize = 30
$totalBlocks = [math]::Ceiling($allQuestions.Count / $blockSize)

for ($b = 0; $b -lt $totalBlocks; $b++) {
    $start = $b * $blockSize
    $end = [math]::Min($start + $blockSize - 1, $allQuestions.Count - 1)
    $block = $allQuestions[$start..$end]
    $blockNum = ($b + 1).ToString("D2")
    $fileName = "block$blockNum.js"
    $filePath = Join-Path $outDir $fileName
    
    $content = "// Security+ SY0-701 - Questions $($start+1) to $($end+1)`n"
    $content += "// Block $($b+1) of $totalBlocks`n"
    $content += "window.QUESTIONS = (window.QUESTIONS || []).concat([`n"
    $content += ($block -join ",`n")
    $content += "`n]);`n"
    
    [System.IO.File]::WriteAllText($filePath, $content, [System.Text.Encoding]::UTF8)
    Write-Host "Created $fileName (questions $($start+1)-$($end+1))"
}

Write-Host "`nTotal: $($allQuestions.Count) questions in $totalBlocks blocks"
